name: Generate Languages SVG
on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-languages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate languages SVG
      uses: huytd/github-statistics@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: output/languages.svg

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/languages.svg
        git commit -m "Update languages" || echo "No changes"
        git push

